---

  - name: Check to see if pm2 core is installed
    shell: npm list --global --depth 1 pm2
    register: results_test
    failed_when: results_test.rc > 1

  - name: Install pm2 core to npm global
    shell: npm install --global pm2
    become: true
    when:
      - results_test.rc == 1


